# vim: ft=toml
# vim: et ts=4 sw=4 sts=4

# Global settings
separator=true
separator_block_width=15
markup=pango

[touchpad]
command=scripts/touchpad-block
color=#ff5555
interval=once
signal=14

[numlock]
command=scripts/numlock-block
color=#ffaa00
interval=once
signal=15

[volume]
command=scripts/volume-block
color=#00bbff
interval=once
signal=10

[brightness]
command=scripts/brightness-block
color=#ffff00
interval=once
signal=13

[cpu_usage]
label= 
command=scripts/cpu-block
interval=5

[memory]
label=RAM 
command=scripts/memory-block
interval=5

# Root Storage (p3) - /
[root_storage]
label=🖴 /:
command=scripts/disk-block /
color=#A6E22E
interval=60

# Home Storage (p4) - /home
[home_storage]
label=🖴 /home:
command=scripts/disk-block /home
color=#66D9EF
interval=60

[battery]
command=scripts/battery-block
interval=20

[wifi]
command=scripts/wifi-block
interval=6

[time]
label=  
command=date '+%Y-%m-%d %H:%M:%S'
color=#FFFFFF
interval=1

[pomodoro]
command=scripts/pomodoro.sh
interval=1

[input]
command=scripts/input-block
color=#66D9EF
interval=once
signal=12

[notification]
command=scripts/notifications-block
color=#66D9EF
interval=once
signal=11

