# Global settings
separator=true
separator_block_width=15
markup=pango

[arch-update]
command=scripts/arch-update-block -y
interval=3600
LABEL=

[numlock]
label=🖩 
command=scripts/numlock-block
color=#ffaa00
interval=once
signal=15

[volume]
command=scripts/volume-block
color=#00bbff
interval=once
signal=10

[brightness]
label=🌣 
command=scripts/brightness-block
color=#ffff00
interval=once
signal=13

[cpu_usage]
label= 
command=scripts/cpu-block
color=#aaaaaa
interval=5

[memory]
label=☷ 
command=scripts/memory-block
color=#aaaaaa
interval=5

# Root Storage (p3) - /
[root_storage]
label=🖴 /:
command=scripts/disk-block /
color=#A6E22E
interval=60

# Home Storage (p4) - /home
[home_storage]
label=🖴 /home:
command=scripts/disk-block /home
color=#66D9EF
interval=60

[battery]
command=scripts/battery-block
color=#aaaaaa
interval=20

[wifi]
command=scripts/wifi-block
interval=6

[time]
command=date '+%Y-%m-%d %H:%M:%S'
color=#aaaaaa
interval=1

[pomodoro]
command=scripts/pomodoro-block
interval=1

[notification]
label=🕭 
command=scripts/notifications-block
color=#66D9EF
interval=once
signal=11

[input]
command=scripts/input-block
color=#66D9EF
interval=once
signal=12

# vim: ft=toml
