#!/usr/bin/env python3
import i3ipc


class ClawModeSwitcher:
    def __init__(self):
        self.previous_mode = "default"
        self.current_mode = "default"
        self.auto_claw = False

    def on_mode_change(self, i3, event):
        mode = event.change

        if mode != self.current_mode:
            self.previous_mode = self.current_mode
            self.current_mode = mode

    def on_window_focus(self, i3, event):
        focused = event.container
        window_class = (focused.window_class or "").lower()

        # if focus is taken away from claw.exe, exit from claw mode
        if window_class == "claw.exe" and self.auto_claw:
            i3.command("mode claw")
        else:
            if self.current_mode == "claw":
                i3.command(f'mode "{self.previous_mode}"')
                self.auto_claw = True
            else:
                self.auto_claw = False


if __name__ == "__main__":
    i3 = i3ipc.Connection()
    controller = ClawModeSwitcher()

    i3.on("mode", controller.on_mode_change)
    i3.on("window::focus", controller.on_window_focus)

    i3.main()
