#!/bin/bash

SCRIPT_DIR="$(dirname "$0")"

# 1. If clicked via mouse OR triggered by Win+Space shortcut
if [[ "$BLOCK_BUTTON" -eq 1 ]]; then
    LAYOUT=$(setxkbmap -query | awk '/layout:/ {print $2}')
    
    # Toggle and apply your specific variants
    if [[ "$LAYOUT" == "us" ]]; then
        setxkbmap -model pc105 -layout ara -variant digits
    else
        setxkbmap -model pc105 -layout us
    fi
fi

# 2. Obtain touchpad state
ICON=" ⌨"
TP_STATE=$(env -uBLOCK_BUTTON "$SCRIPT_DIR/touchpad-block")
[[ "$TP_STATE" == "OFF" ]] && ICON="${ICON/ /\"}"

# 3. Print
setxkbmap -query | awk -v icon="$ICON " '/layout:/ { l=toupper($2); print icon (length(l)<3 ? l"  " : l) }'
