#!/bin/sh

while getopts "c:p:" opt
do
    case "$opt" in
        c) CMD="$OPTARG" ;;
        p) PROMPT="$OPTARG" ;;
    esac
done
shift $((OPTIND - 1))

color1=${1:-#000}
color2=${2:-#fff}

if [[ $# -ge 2 ]]
then
    shift 2
else
    shift $#
fi

"${CMD:-dmenu}" \
    -i          \
    -b          \
    -nb $color1 \
    -nf $color2 \
    -sf $color1 \
    -sb $color2 \
    -p ${PROMPT:-Dmenu} \
    -fn Hack    \
    "$@"
