#!/bin/bash

TP_ID=$(xinput list | grep -i "touchpad" | grep -oP 'id=\K\d+' | head -n 1)
state=$(xinput list-props "$TP_ID" | grep "Device Enabled" | awk '{print $4}')

# Read and display the current state
if [[ "$state" -eq 1 ]]
then
    echo "ON "
else
    echo "OFF"
fi
