# Enable 256-color and true-color (24-bit) support in tmux
set -g default-terminal "screen-256color" # Set terminal type for 256-color support
set -ga terminal-overrides ",*256col*:Tc" # Override to enable true-color for compatible terminals

# General
set -g mouse on
set -s escape-time 0
set -g status-interval 3
set -g detach-on-destroy off

# Set prefix key
unbind C-b
set -g prefix M-f
bind-key M-f send-prefix

# Refresh tmux config with r
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# splitting and creating windows in CWD
unbind %
unbind \"
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Use vim arrow keys to resize
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r m resize-pane -Z # maximize pane

# Copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# Natural window numbering
set -g base-index 1
set -g pane-base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# List of tmux plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator' # Enable navigating between nvim and tmux
set -g @plugin 'tmux-plugins/tmux-resurrect'    # Persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum'    # Automatically saves sessions every 15 minutes
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor' # CPU and memory info

set -g status-position bottom
set -g status-justify centre
set -g status-right-length 100
set -g status-left-length 100
set -g status-right " #{cpu -i 3} |  #{mem} "

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'

# Style
gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

set -g status-style "bg=${gray_dark}"
set -g status-left "#[fg=${green_soft},bold,bg=${gray_dark}]  #S"
set -g window-status-current-format "#[fg=${cyan_soft},bg=default]  #I:#W"
set -g window-status-format "#[fg=${gray_light},bg=default] #I:#W"
set -g window-status-last-style "fg=${gray_light},bg=default"
set -g pane-active-border-style "fg=${gray_medium},bg=default"
set -g pane-border-style "fg=brightblack,bg=default"

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

# vim: ft=tmux
