"""i3gen — engine for describing i3 keybindings in Python.

This holds the reusable machinery so the descriptive config (i3config.py) stays
clean. Two responsibilities:

  1. Translation logic. This i3 build has no `bindsym --to-code`, so keysym
     bindings break under non-Latin layouts (e.g. Arabic: physical `c` emits
     `ؤ`, `l` emits `/`). Keycodes are physical positions that never change with
     the layout, so `translate()` emits `bindcode` for keys we can resolve and
     leaves named/layout-immune keys (Return, arrows, Print, ...) as `bindsym`.

  2. A tiny builder (`Keymap`) that accumulates lines, supports `mode` blocks
     via a context manager, and renders/writes the final i3 include file.

Extend freely: add helpers here, keep declarations in i3config.py.
"""

from __future__ import annotations

from contextlib import contextmanager
from pathlib import Path

# Canonical US pc105 keysym -> X keycode (X keycode = Linux evdev code + 8).
# Deliberately static: generation is deterministic and stays correct even if run
# while a non-Latin layout is active, because these are physical key positions.
KEYCODES: dict[str, int] = {
    "1": 10,
    "2": 11,
    "3": 12,
    "4": 13,
    "5": 14,
    "6": 15,
    "7": 16,
    "8": 17,
    "9": 18,
    "0": 19,
    "q": 24,
    "w": 25,
    "e": 26,
    "r": 27,
    "t": 28,
    "y": 29,
    "u": 30,
    "i": 31,
    "o": 32,
    "p": 33,
    "bracketleft": 34,
    "bracketright": 35,
    "a": 38,
    "s": 39,
    "d": 40,
    "f": 41,
    "g": 42,
    "h": 43,
    "j": 44,
    "k": 45,
    "l": 46,
    "semicolon": 47,
    "apostrophe": 48,
    "grave": 49,
    "z": 52,
    "x": 53,
    "c": 54,
    "v": 55,
    "b": 56,
    "n": 57,
    "m": 58,
    "comma": 59,
    "period": 60,
    "slash": 61,
    "space": 65,
}


def translate(combo: str) -> str:
    """Return the i3 binding directive (`bindcode ...` or `bindsym ...`) for a combo.

    The bound key is the last '+'-separated element; everything before it is the
    modifier prefix. If the key has a known keycode we emit layout-independent
    `bindcode`; otherwise we keep the keysym with `bindsym`.
    """
    if "+" in combo:
        mods, key = combo.rsplit("+", 1)
        mods += "+"
    else:
        key = combo
        mods = ""

    code = KEYCODES.get(key)
    if code is None:
        return f"bindsym {combo}"
    return f"bindcode {mods}{code}"


class Keymap:
    """Accumulates i3 config lines described in Python, then renders them."""

    INDENT = "    "

    def __init__(self) -> None:
        self._lines: list[str] = []
        self._depth = 0

    # --- low-level line helpers -------------------------------------------
    def raw(self, text: str = "") -> None:
        """Emit a verbatim line (or a blank line when text is empty)."""
        self._lines.append(f"{self.INDENT * self._depth}{text}" if text else "")

    def blank(self) -> None:
        self._lines.append("")

    def comment(self, text: str) -> None:
        self.raw(f"# {text}")

    # --- bindings ---------------------------------------------------------
    def bind(self, combo: str, command: str, flags: str = "") -> None:
        """Bind a key combo to a command, auto-choosing bindcode vs bindsym.

        `flags` is an optional space-separated string of binding flags i3
        understands (e.g. "--release"); it is inserted right after the keyword.
        """
        directive = translate(combo)
        if flags:
            keyword, rest = directive.split(" ", 1)
            directive = f"{keyword} {flags} {rest}"
        self.raw(f"{directive} {command}")

    @contextmanager
    def mode(self, name: str):
        """Open a `mode "<name>" { ... }` block; bindings inside are indented."""
        self.raw(f'mode "{name}" {{')
        self._depth += 1
        try:
            yield self
        finally:
            self._depth -= 1
            self.raw("}")

    # --- output -----------------------------------------------------------
    def render(self, source: str = "i3config.py") -> str:
        header = (
            f"# AUTO-GENERATED by {source} — DO NOT EDIT.\n"
            f"# Edit {source} and run it (or press $mod+Shift+c in i3) to regenerate.\n"
        )
        body = "\n".join(self._lines)
        return f"{header}\n{body}\n"

    def write(self, path: str | Path, source: str = "i3config.py") -> Path:
        path = Path(path)
        path.write_text(self.render(source))
        return path
