#!/usr/bin/env sh

BAT="${BAT:-/sys/class/power_supply/BAT0}"
CAPACITY=$(cat "$BAT/capacity")
STATUS=$(cat "$BAT/status")
CYCLE_COUNT=$(cat "$BAT/cycle_count")
STATE_FILE="${STATE_FILE:-$HOME/.local/state/battery_notified}"

# Ensure the state directory exists
mkdir -p "${STATE_FILE%/*}"

# 1. Choosing an icon
case "$STATUS" in
    (Charging)      ICON="⚡" ;;
    (Discharging)   ICON=""  ;;
    (Full)          ICON="🔌" ;;
    (*)             ICON="🔋" ;;
esac

# 2. Full and short text
echo "$ICON $CAPACITY% ($CYCLE_COUNT)"
echo "$ICON $CAPACITY%"

# 3. Critical threshold
if [[ "$CAPACITY" -le 20 && "$STATUS" == "Discharging" ]]
then
    if [[ ! -f "$STATE_FILE" ]]
    then
        touch "$STATE_FILE"
        notify-send -u critical "Battery Low"\
            "Plug in your charger! Capacity at ${CAPACITY}%."
    fi
    echo "#FFFFFF"
    exit 33  # urgent exit code, this sets the background to red
fi

rm -f "$STATE_FILE"
exit 0
